# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            memory: 
                users: 
                    paul: 
                        password: birthday 
                        roles: 'ROLE USER'
                    admin: 
                        password: $2y$12$Qhsq29zDooUljui1l6mKUudu4MBTj5Xu3Lw6LeAK.BtB74NUvW40G  
                        roles: 'ROLE_ADMIN'
    encoders: 
        Symfony\Component\Security\Core\User\User: 
            algorithm: bcrypt 
            cost: 12

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            # activate different ways to authenticate

            # http://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            form_login:
                login_path: login 
                check_path: login

            logout:
                path:    /logout 
                target: / # url de redirection


            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
            #form_login: ~

    access_control: 
        - {path: ^/admin, roles : ROLE_ADMIN}