# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value
    customer.balance_watcher.balance: 0

services:
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']
    customer.balance_watcher:
        class: CustomerBundle\Service\BalanceWatcher 
        arguments:
            - '@doctrine.orm.default_entity_manager'
